version: '3'
services:
  nodeapp:
    container_name: docker-mongo-resource
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: env/development.env
    ports:
      - '7002:7002'
    depends_on:
      - mongo

  mongo:
    container_name: mongodb-container
    image: mongo
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb:
